### ISSUE TITLE
Coal Coke Block should be crushable

### ISSUE THREAD

**Issue by yonsaber** [Hanse00/CrafTech-old#26]
Simple, the item is crushable, the block should be as well.

Crushes to 18 dust, is this too much?

Thoughts @Hanse00 ?

**Comment by Hanse00** [comment]
18 seems like the only logical value, as long as one coke becomes two dust. Otherwise players are just pushed towards un-crafting the block before crushing.

But maybe the real question is, should the coke block be crushable in the first place? I don't think it hurts for the user to have to turn their blocks into items first.
If we do let the blocks be crushed, at least I think it should take 9x the time to crush one, compared to the items.

**Comment by yonsaber** [comment]
You do get 2 dust from one item.
I was thinking that as the rest of the items we put in the crusher are blocks, do we only allow coal coke blocks to be crushed and not the item.

**Comment by Hanse00** [comment]
Because the other things don't have an item equivalent, it makes sense to me to go with the smaller physical item.

A big of coke makes more sense to crush, than a whole cubic meter of it.

**Comment by yonsaber** [comment]
Okay, so we will leave it as is. I'm happy with that

**Comment by Hanse00** [comment]
In that case I'm closing the issue, we can always return later.
